# Generated by Django 3.2.10 on 2022-03-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invite_code',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='کد معرفی '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar-defualt.png', upload_to='uploads/profile', verbose_name='عکس کاربر'),
        ),
    ]
