# Generated by Django 3.2.10 on 2022-03-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220306_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام سرویس')),
                ('slug', models.SlugField(verbose_name='اسلاگ')),
                ('available', models.BooleanField(verbose_name='در دسترس')),
                ('short_description', models.CharField(max_length=50, verbose_name='توضیح کوتاه ')),
            ],
        ),
    ]
