# Generated by Django 3.2.10 on 2022-03-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220308_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='use_invite_code',
            field=models.BooleanField(default=False, verbose_name='استفاده از کد معرف'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='cash',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی کیف پول'),
        ),
    ]
