# Generated by Django 3.2.10 on 2022-03-19 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('account', '0006_categorystamp_essencestamp_shapestamp_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_payment', models.CharField(choices=[('PID', 'پرداخت شده'), ('CNL', 'کنسل شده'), ('PND', 'در حال پردازش'), ('CFD', 'تایید شده')], default='PND', max_length=3, verbose_name='وضعیت پرداخت')),
                ('order_number', models.CharField(blank=True, max_length=23, null=True, unique=True, verbose_name='شماره سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('paid_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت پرداختی')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='categorystamp',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='essencestamp',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='shapestamp',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='اسلاگ'),
        ),
        migrations.CreateModel(
            name='EvidenceStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.FileField(upload_to='uploads/evidence-stamp', verbose_name='مدرک اصلی')),
                ('evidence2', models.FileField(blank=True, null=True, upload_to='uploads/evidence-stamp', verbose_name='مدرک اصلی ۲')),
                ('sketch_stamp', models.FileField(upload_to='uploads/sketch-stamp', verbose_name='طرح مهر')),
                ('note', models.TextField(verbose_name='یادداشت')),
                ('is_framework', models.BooleanField(verbose_name='دارای کادر')),
                ('is_confirmed', models.BooleanField(blank=True, null=True, verbose_name='تایید شده')),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.stamp', verbose_name='مهر مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, verbose_name='شماره شی')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.PositiveIntegerField(blank=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.cart')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
