# Generated by Django 3.2.10 on 2022-04-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220404_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencestamp',
            name='evidence',
            field=models.ImageField(upload_to='uploads/evidence-stamp', verbose_name='مدرک اصلی'),
        ),
        migrations.AlterField(
            model_name='evidencestamp',
            name='evidence2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/evidence-stamp', verbose_name='مدرک اصلی ۲'),
        ),
        migrations.AlterField(
            model_name='evidencestamp',
            name='sketch_stamp',
            field=models.ImageField(upload_to='uploads/sketch-stamp', verbose_name='طرح مهر'),
        ),
    ]
